### ISSUE TITLE
AADSTS7000218 Exception

### ISSUE THREAD

**Issue by samwdp** [Azure-Samples/active-directory-dotnetcore-console-up-v2#10]
Run the example and I get:

>{\"error\":\"invalid_client\",\"error_description\":\"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\\r\\nTrace ID: beccd714-f79a-4886-96e7-e1ad0ca33f00\\r\\nCorrelation ID: 51a39edf-8fd5-4fed-81c6-ac744e08b654\\r\\nTimestamp: 2019-03-04 11:00:32Z\",\"error_codes\":[7000218],\"timestamp\":\"2019-03-04 11:00:32Z\",\"trace_id\":\"beccd714-f79a-4886-96e7-e1ad0ca33f00\",\"correlation_id\":\"51a39edf-8fd5-4fed-81c6-ac744e08b654\"}

### Mention any other details that might be useful
App Registration has full permissions Application and Delegated
Happens at line 95 in PublicClientApplication

**Comment by samwdp** [comment]
Tried to change the App Registration manifest but get this error: 
Failed to save manifest. Error details: Could not find member 'allowPublicClient' on object of type 'ApplicationDetails

**Comment by jmprieur** [comment]
@samwdp : how did you create your application? using the new app registration in the portal?

**Comment by samwdp** [comment]
@jmprieur  through the none-preview version, It is an established app registration that is being used to authenticate with other azure clients

**Comment by jmprieur** [comment]
@samwdp : Then did you try to edit the manifest through the new app registration? or through the old one?
(you'd need to do it through the new one to see this field. The property in old manifest was, if I remember correctly IsPublicClient=true or something like that.

**Comment by samwdp** [comment]
@jmprieur I just did this before coming here and it works. Thanks for taking the time.

**Comment by jmprieur** [comment]
closing as this is working for you
