### ISSUE TITLE
Possible to run the code without admin consent permission

### ISSUE THREAD

**Issue by quantrpeter** [Azure-Samples/active-directory-dotnetcore-console-up-v2#27]
Hi
  Possible to run the code without admin consent permission?
Thanks
From Peter

**Comment by jmprieur** [comment]
Hi @quantrpeter 
Given that the user cannot consent (username password is a silent flow the user is not presented a dialog), the admin needs to consent.

**Comment by quantrpeter** [comment]
Thanks @jmprieur
