### ISSUE TITLE
reading other tenant (multi-tenant) is not working

### ISSUE THREAD

**Issue by quantrpeter** [Azure-Samples/active-directory-dotnetcore-console-up-v2#28]
Hi
    I can use this project to read my tenant successfully. But when i try to read from other tenant, it doesn't work. I tried to this project (https://github.com/azure-samples/active-directory-dotnet-desktop-msgraph-v2) to read other tenant, it popup a dialog to ask for my "Consent", then i rerun this project, it becomes work. So I guess this project is missing code to "consent" the permission, right?
Thank
From Peter

**Comment by jmprieur** [comment]
@quantrpeter : users necessarily need to consent (once) for an application to access their resources. There is no code that can consent for the user.

Alternatively tenant admins can consent for users: See bullet point 7 in https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2#register-the-client-app-up-console

**Comment by quantrpeter** [comment]
thank you Mr Jumprieur
