### ISSUE TITLE
AADSTS70002 Exception

### ISSUE THREAD

**Issue by Devolick** [Azure-Samples/active-directory-dotnetcore-console-up-v2#4]
Hi, I had write this code with link below. I just want take token for current user. But I got exception:

**"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'\r\nTrace ID: c0ed24d9-07a6-4be7-9e35-69e6f3151301\r\nCorrelation ID: a09ac498-6d3e-4765-89ed-6252cab3ccac\r\nTimestamp: 2018-11-26 13:13:25Z"**

[OutlookEWSTest.zip](https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2/files/2615670/OutlookEWSTest.zip)

**Comment by jmprieur** [comment]
@Devolick : did you change the `allowPublicClient` property of the manifest to true?
See bullet item number 4 of https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2#register-the-client-app-up-console

See also the explanation of the exception in the code:
https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2/blob/master/up-console/PublicAppUsingUsernamePassword.cs#L170

**Comment by Devolick** [comment]
> @Devolick : did you change the `allowPublicClient` property of the manifest to true?
> See bullet item number 4 of https://github.com/Azure-Samples/active-directory-dotnetcore-console-up-v2#register-the-client-app-up-console

Thank you. I miss that, now I got token.

**Comment by jmprieur** [comment]
Thanks for confirming. Feel free to close the issue
