### ISSUE TITLE
Error: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access

### ISSUE THREAD

**Issue by hellopuneet4** [Azure-Samples/active-directory-dotnetcore-console-up-v2#44]
I just followed the steps motioned but end up getting below error- 

Error: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access

Can someone help me?

**Comment by jmprieur** [comment]
@hellopuneet4. What happens is that:
- the tenant admin has setup conditional access.
- Username/Password cannot handle it. For details see [Desktop app that calls web APIs: Acquire a token | Username and password flow isn't recommended](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-acquire-token?tabs=dotnet#this-flow-isnt-recommended)

You need to use an interactive flow. See https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#desktop-and-mobile-public-client-apps for other desktop samples.
